name: Create Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_run:
    workflows: ["Version Bump"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Latest Tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        id: previous-tag
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.previous-tag.outputs.tag }}
